CREATE DATABASE CarpoolingEL;
use CarpoolingEL;

CREATE TABLE TIPO_USUARIO (
	idTipoUser INTEGER IDENTITY(1,1) PRIMARY KEY NOT NULL,
	descTipo VARCHAR(64) NOT NULL
);

CREATE TABLE USUARIOS (
	idUsu INTEGER IDENTITY(1,1) PRIMARY KEY NOT NULL,
	nomeUsu VARCHAR(120) NOT NULL,
	emailUsu VARCHAR(120) NOT NULL,
	rgUsu VARCHAR(10) NOT NULL,
	endUsu VARCHAR (120) NOT NULL,
	compUsu VARCHAR(120),
	cepUsu VARCHAR(8) NOT NULL,
	bairroUsu VARCHAR(120) NOT NULL,
	cidadeUsu VARCHAR(120) NOT NULL,
	ufUsu CHAR(2) NOT NULL,
	telUsu VARCHAR(11) NOT NULL,
	celUsu VARCHAR (11) NOT NULL,
	usuario VARCHAR(120) NOT NULL,
	senha VARCHAR(120) NOT NULL,
	fkTipo INTEGER,
	CONSTRAINT fkTipoUser FOREIGN KEY (fkTipo) REFERENCES TIPO_USUARIO(idTipoUser)
);

CREATE TABLE DESTINOS (
	idDest INTEGER IDENTITY(1,1) PRIMARY KEY NOT NULL,
	endDest VARCHAR(120) NOT NULL,
	compDest VARCHAR(120),
	cepDest VARCHAR(8) NOT NULL,
	bairroDest VARCHAR(120) NOT NULL,
	cidadeDest VARCHAR(120) NOT NULL,
	ufDest CHAR(2) NOT NULL,
	fkUsu INTEGER,
	CONSTRAINT fkUsuIDCarDest FOREIGN KEY (fkUsu) REFERENCES USUARIOS(idUsu)
);


CREATE TABLE CARROS (
	idCar INTEGER IDENTITY(1,1) PRIMARY KEY NOT NULL,
	modeloCar VARCHAR(120) NOT NULL,
	placaCar VARCHAR(8) NOT NULL,
	corCar VARCHAR(120) NOT NULL,
	capacidadeCar INTEGER NOT NULL,
	fkUsu INTEGER,
	CONSTRAINT fkUsuIDCar FOREIGN KEY (fkUsu) REFERENCES USUARIOS(idUsu)
);

CREATE TABLE AGENDA (
	idAge INTEGER IDENTITY(1,1) PRIMARY KEY NOT NULL,
	dhAge DATETIME NOT NULL, --dh = data e hora XD rsrs
	fkCar INTEGER,
	fkDest INTEGER,
	fkUsu INTEGER,
	CONSTRAINT fkCarID FOREIGN KEY (fkCar) REFERENCES CARROS(idCar),
	CONSTRAINT fkDestID FOREIGN KEY (fkDest) REFERENCES DESTINOS(idDest),
	CONSTRAINT fkUsuIDAge FOREIGN KEY (fkUsu) REFERENCES USUARIOS(idUsu)
);

CREATE TABLE AGENDA_USUARIOS (
	idAgeUsu INTEGER IDENTITY(1,1) PRIMARY KEY NOT NULL,
	fkAge INTEGER,
	fkUsu INTEGER,
	CONSTRAINT fkAgeID FOREIGN KEY (fkAge) REFERENCES AGENDA(idAge),
	CONSTRAINT fkUsuIDAgeUsu FOREIGN KEY (fkUsu) REFERENCES USUARIOS(idUsu)
);

INSERT INTO TIPO_USUARIO VALUES ('Passageiro');
INSERT INTO TIPO_USUARIO VALUES ('Motorista');
