//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarpoolingEL
{
    using System;
    using System.Collections.Generic;
    
    public partial class DESTINOS
    {
        public DESTINOS()
        {
            this.AGENDA = new HashSet<AGENDA>();
        }
    
        public int idDest { get; set; }
        public string endDest { get; set; }
        public string compDest { get; set; }
        public string cepDest { get; set; }
        public string bairroDest { get; set; }
        public string cidadeDest { get; set; }
        public string ufDest { get; set; }
        public Nullable<int> fkUsu { get; set; }
    
        public virtual ICollection<AGENDA> AGENDA { get; set; }
        public virtual USUARIOS USUARIOS { get; set; }
    }
}
