//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarpoolingEL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TIPO_USUARIO
    {
        public TIPO_USUARIO()
        {
            this.USUARIOS = new HashSet<USUARIOS>();
        }
    
        public int idTipoUser { get; set; }
        public string descTipo { get; set; }
    
        public virtual ICollection<USUARIOS> USUARIOS { get; set; }
    }
}
